#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= ARGV[0] || 'development'
worker_index = ARGV[1] || Process.pid
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

Delayed::Job.worker_name = "dj.#{Rails.env}.#{worker_index}@#{Socket.gethostname}"

Delayed::Worker.logger = ActiveSupport::BufferedLogger.new(Rails.root.join('log', "delayed_job_#{Rails.env}.log"))
Delayed::Worker.new(:min_priority => ENV['MIN_PRIORITY'], :max_priority => ENV['MAX_PRIORITY'], :quiet => true).start